import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../providers";
import AppBar from "../components/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wallet App",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>
          <div className="bg-[#EBE6E6] min-h-screen">
            <AppBar />
              {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
